### ISSUE TITLE
echo/noise problem with speaker

### ISSUE THREAD

**Issue by fukemy** [Meonardo/janus-videoroom-ios#10]
hi, i got echo problem when set speakerOn(), did u test with this case?:

```
let mandatoryConstraints =
            ["googEchoCancellation"        : "false",
             "echoCancellation"            : "false",
             "googNoiseSuppression"        : "false",
             "googCpuOveruseDetection"     : "false"]
        // Define media constraints. DtlsSrtpKeyAgreement is required to be true to be able to connect with web browsers.
        let constraints = RTCMediaConstraints(mandatoryConstraints: mandatoryConstraints,
                                              optionalConstraints: ["DtlsSrtpKeyAgreement": kRTCMediaConstraintsValueTrue])
```

**Comment by Meonardo** [comment]
> hi, i got echo problem when set speakerOn(), did u test with this case?:

Hi, sorry for the late reply, what is your test environment?

**Comment by Meonardo** [comment]
`googEchoCancellation ...` first time I saw these constants, maybe they're not working in iOS platform(if these value turn to true).
Did you accidentally have your two devices with both mic on in the same room?

**Comment by fukemy** [comment]
it's still make echo when 2 ios device using speaker (small closed room), i can hear the voice is double

**Comment by Meonardo** [comment]
> 2 ios device using speaker (small closed room)

that's make sense, I think its normal phenomenon. 
Can you try to use FaceTime audio to test this usecase?

**Comment by fukemy** [comment]
i tried viber, facetime, and it's work normally. only my app make echo... i'm trying to fix this by searching all issues that related to echo problem

**Comment by fukemy** [comment]
i think when using speaker, the voice from speaker(which send from A) is recorded then send back to A

**Comment by fukemy** [comment]
close because found problem
