### ISSUE TITLE
 failed extracting 'https://github.com/Meonardo/WebRTC/releases/download/91.0.1/WebRTC-M91.0.1.xcframework.zip' which is required by binary target 'WebRTC': /Users/..../Library/Developer/Xcode/DerivedData/janus-videoroom-example-blqhidmhjqwphtfdlfbubclciaic/SourcePackages/artifacts/extract/WebRTC is not a directory

### ISSUE THREAD

**Issue by fukemy** [Meonardo/janus-videoroom-ios#3]
hi can u help? Thanks

**Comment by Meonardo** [comment]
The WebRTC.framework file size is huge, maybe you have not download this file completely.
You can try download this file from https://github.com/Meonardo/WebRTC/releases/download/91.0.1/WebRTC-M91.0.1.xcframework.zip ,
then drag this file to your project.
FYI: the `WebRTC.framework` is unofficial WebRTC framework from Google.

**Comment by fukemy** [comment]
i can run project even there still have this warning. may be xcode problem, thanks for great library
