### ISSUE TITLE
how to change state of button(mic/camera/speaker) automatic

### ISSUE THREAD

**Issue by fukemy** [Meonardo/janus-videoroom-ios#6]
Hi, i saw these above buttons is automatically change state when publish/not publish camera
![Ảnh chụp Màn hình 2021-10-09 lúc 21 52 33](https://user-images.githubusercontent.com/8202437/136663127-6e1ed351-a00c-481b-a915-10934a7d2a27.png)
 when join as subscriber these button is not enabled, but after publish all button can interact( without click event), i tried to find anything related to this button but can not find. Can you give me some advices, it's really magic for me

**Comment by Meonardo** [comment]
First, you can find any [events](https://github.com/Meonardo/janus-videoroom-ios/blob/b7b4b4ea20ecefdb0bdc8e49051105397308c7d4/janus-videoroom-example/Views/VideoRoomViewController.swift#L211) belongs to the `UISwitch` ;
Then, this line of code do the job for changing the buttons state.
```
functionStackView.arrangedSubviews.compactMap({ $0 as? UIButton }).forEach({ $0.isEnabled = true })
```
