### ISSUE TITLE
is this starcream bug: connected state called again after disconnect() socket

### ISSUE THREAD

**Issue by fukemy** [Meonardo/janus-videoroom-ios#7]
hi, im trying to disconnect the socket when leaved call using:
```
@objc private func roomStateDidChange(_ sender: Notification) {
        guard let roomState = sender.object as? JanusRoomState else { return }
        
        ProgressHUD.dismiss()
        
        if roomState == .left {
            roomManager.disconnect()
            dismiss(animated: true, completion: nil)
        }
    }
```

But when debug i found the state connected is called again, dont know why. here is the log:

```
==============> Send WebSocket Message: {"janus":"destroy","transaction":"Destroy","session_id":5125526605993175} 

"peerConnection new connection state: disconnected"
Connection state did change: disconnected
<============== Receive WebSocket Message: {
   "janus": "success",
   "session_id": 5125526605993175,
   "transaction": "Destroy"
} 

2021-10-10 16:06:22.092131+0700 janus-videoroom-example[15297:524784] [tcp] tcp_input [C1.1:2] flags=[R] seq=4068253224, ack=0, win=0 state=CLOSED rcv_nxt=4068253224, snd_una=3875245229
VideoViewController is deinit...
WebRTCClient is deinit...
```

here is the debug time i got:
![Ảnh chụp Màn hình 2021-10-10 lúc 16 10 14](https://user-images.githubusercontent.com/8202437/136689653-2fd3c175-c288-44ca-a451-ea3cfdc7c8fb.png)

it's seem the socket does not closed immediately but its connected again

**Comment by fukemy** [comment]
it's seem startcream bug: https://github.com/daltoniam/Starscream/issues/919, i tried to using method forceDisconnected then it's triggered cancelled state. 
 Im really sorry for bothering you many times

**Comment by Meonardo** [comment]
> it's seem startcream bug: [daltoniam/Starscream#919](https://github.com/daltoniam/Starscream/issues/919), i tried to using method forceDisconnected then it's triggered cancelled state. Im really sorry for bothering you many times

No worries! 

> found the state connected is called again.

I want to the connection always on so I did this on purpose😁 (please see [line 274](https://github.com/Meonardo/janus-videoroom-ios/blob/b7b4b4ea20ecefdb0bdc8e49051105397308c7d4/janus-videoroom-example/Source/SignalingClient.swift#L274) & line 289), 
while the `SignalingClient` receive `disconnect` or `cancelled` callback, the client call `reconnect()` right away,
so the socket connects again.

You can just comment this `reconnect()` or add your own conditions.
